### ISSUE TITLE
Can't install NodeJS gl-client on Mac M1 

### ISSUE THREAD

**Issue by bilthon** [Blockstream/greenlight#179]
Here's the stack trace I get when ran `npm install`

```
npm ERR! code 101
npm ERR! path /Users/bilthon/Development/Node/Demo/greenlight-test/node_modules/gl-client
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build=false || npm run build
npm ERR! response status 404 Not Found on https://storage.googleapis.com/greenlight-artifacts/npm/gl-client-js/0.1.9/gl-client-0.1.9-darwin-x64.tar.gz
npm ERR! 
npm ERR! > gl-client@0.1.9 build
npm ERR! > cargo-cp-artifact -a cdylib gl_client_js index.node -- cargo build --message-format=json-render-diagnostics --release
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@14.20.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/bilthon/Development/Node/Demo/greenlight-test/node_modules/gl-client/index.node" (not found)
npm ERR! node-pre-gyp http GET https://storage.googleapis.com/greenlight-artifacts/npm/gl-client-js/0.1.9/gl-client-0.1.9-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/greenlight-artifacts/npm/gl-client-js/0.1.9/gl-client-0.1.9-darwin-x64.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://storage.googleapis.com/greenlight-artifacts/npm/gl-client-js/0.1.9/gl-client-0.1.9-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /Users/bilthon/Development/Node/Demo/greenlight-test/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/bilthon/.fnm/node-versions/v14.20.0/installation/bin/node" "/Users/bilthon/Development/Node/Demo/greenlight-test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /Users/bilthon/Development/Node/Demo/greenlight-test/node_modules/gl-client
npm ERR! node-pre-gyp ERR! node -v v14.20.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! error: failed to parse manifest at `/Users/bilthon/Development/Node/Demo/greenlight-test/node_modules/gl-client/Cargo.toml`
npm ERR! 
npm ERR! Caused by:
npm ERR!   can't find library `gl_client_js`, rename file to `src/lib.rs` or specify lib.path
npm ERR! Did not copy "cdylib:gl_client_js"

npm ERR! A complete log of this run can be found in: /Users/bilthon/.npm/_logs/2023-06-16T21_20_48_066Z-debug-0.log
```

I suppose it's the lack of pre-compiled binaries as mentioned in the README, right? But if so, how do I compile them? The `npm update` also didn't work.

**Comment by cdecker** [comment]
The problem stems from the fact that we have a multi-crate repository, but only the gl-client-js crate source is being bundled in the JS source distribution. Since that depends on `gl-client` (the Rust library) and that is not distributed compilation fails.

You can build by checking out the code, and then running `npm run build` in the `libs/gl-client-js` directory, and then depending on the built library path from your project.

As for the precompiled library, it's there, but there seems to be a mismatch between architecture tag being searched (gl-client-0.1.9-darwin-x64.tar.gz) and the tag that is there (gl-client-0.1.9-darwin-x86_64.tar.gz) (notice the `x64` vs `x86_64`).

Not being a JS packaging expert, I might have gotten this wrong, but I expected the arch to correspond to `console.log(process.arch)` when looking for precompiled bundles.

**Comment by cdecker** [comment]
Ok, so we created a copy of the binary, so it should now be found by the downloader script.
