### ISSUE TITLE
prebuilt glcli is outdated

### ISSUE THREAD

**Issue by rolznz** [Blockstream/greenlight#354]
https://github.com/Blockstream/greenlight?tab=readme-ov-file#install-and-updating-glcli-and-python-api does not have this fix commit: https://github.com/Blockstream/greenlight/commit/2dc5a94668d41baef7275dae860c09b4a5dba198 

So basic commands like `glcli getinfo` fail.

**Comment by steepdawn974** [comment]
Can confirm. Getting this error when running `glcli getinfo`

```
[2024-02-23 14:02:58,992 - INFO] Configuring client with user identity.
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/gl/bin/glcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/glcli/cli.py", line 348, in getinfo
    pbprint(res)
  File "/home/user/.pyenv/versions/gl/lib/python3.12/site-packages/glcli/cli.py", line 230, in pbprint
    print(json.dumps(dta))
          ^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.0/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.0/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.0/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.0/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

```

**Comment by yshwanth** [comment]
Is it updated ?
